@startuml Aggregator actions
title Aggregator actions
!theme cerulean
!include <material/common>
!include <material/script.puml>

skinparam maxMessageSize 150
skinparam defaultTextAlignment center
skinparam noteTextAlignment left
skinparam backgroundColor White
skinparam SequenceParticipantBorderThickness 0
skinparam ParticipantBackgroundColor Transparent
skinparam ParticipantFontColor Black

actor "Aggregator" as ag
participant "MA_SCRIPT(#2fa4e7, 1)\nMarketplace" as ma #White

== Propose match ==
ag<--ma: Gather offers logs
ag<--ma: Gather demands logs
ag->ma ++: Submit new match proposal
ma->ma: Validate parameters
ma->ma: Check compatibility
ma->ma: Lock offer and demand
note over ma: Log new match proposal
ma-->>ag --

== Cancel match ==
ag<--ma: Gather matches logs
ag->ma ++: Cancel match proposal
ma->ma: Check match still pending
ma->ma: Unlock offer and demand
ma->ma: Delete match
note over ma: Log match cancelled
ma-->>ag --


@endpuml