@startuml Buyer actions
title Buyer actions
!theme cerulean
!include <material/common>
!include <material/script.puml>

skinparam maxMessageSize 150
skinparam defaultTextAlignment center
skinparam noteTextAlignment left
skinparam backgroundColor White
skinparam SequenceParticipantBorderThickness 0
skinparam ParticipantBackgroundColor Transparent
skinparam ParticipantFontColor Black

actor "Buyer" as bu
participant "MA_SCRIPT(#2fa4e7, 1)\nMarketplace" as ma #White

== Submit demand ==
bu->ma ++: Submit new/updated demand
ma->ma: Validate parameters
ma->ma: Check demand is unlocked
note over ma: Log new/updated demand
ma-->>bu --

== Cancel demand ==
bu->ma ++: Cancel demand
ma->ma: Check demand is unlocked
note over ma: Log demand cancelled
ma-->>bu --

== Reject match proposal ==
bu<--ma: Gather matches logs
bu->ma ++: Reject match proposal
ma->ma: Check match still pending
ma->ma: Unlock offer and demand
ma->ma: Delete match
note over ma: Log match rejected
ma-->>bu --

== Delete match ==
bu<--ma: Gather matches logs
bu->ma ++: Reject match proposal
ma->ma: Check match accepted
ma->ma: Unlock offer and demand
ma->ma: Delete match
note over ma: Log match deleted
ma-->>bu --
@enduml