@startuml Owner actions
title Owner actions
!theme cerulean
!include <material/common>
!include <material/script.puml>

skinparam maxMessageSize 150
skinparam defaultTextAlignment center
skinparam noteTextAlignment left
skinparam backgroundColor White
skinparam SequenceParticipantBorderThickness 0
skinparam ParticipantBackgroundColor Transparent
skinparam ParticipantFontColor Black

actor "Owner" as ow
participant "MA_SCRIPT(#2fa4e7, 1)\nMarketplace" as ma #White
participant "MA_SCRIPT(#2fa4e7, 1)\nIdentity Manager" as im #White
participant "MA_SCRIPT(#2fa4e7, 1)\nDID" as DID #White

== Create DID ==
ow->im ++: Create new DID request
im->DID **: Deploy clone DID contract
note over im: Log new DID
im-->>ow --

== Submit offer ==
ow->ma ++: Submit new/updated offer
ma->ma: Validate parameters
ma->ma: Check offer is unlocked
ma->im ++: Check DID ownership
im->ma --: DID ownership validated
note over ma: Log new/updated offer
ma-->>ow --

== Cancel offer ==
ow->ma ++: Cancel offer
ma->ma: Check offer is unlocked
ma->im ++: Check DID ownership
im->ma --: DID ownership validated
note over ma: Log offer cancelled
ma-->>ow --

== Reject match proposal ==
ow<--ma: Gather matches logs
ow->ma: Reject match proposal
ma->im ++: Check DID ownership
im->ma --: DID ownership validated
ma->ma: Check match still pending
ma->ma: Unlock offer and demand
ma->ma: Delete match
note over ma: Log match rejected
ma-->>ow --

== Delete match ==
ow<--ma: Gather matches logs
ow->ma ++: Reject match proposal
ma->im ++: Check DID ownership
im->ma --: DID ownership validated
ma->ma: Check match accepted
ma->ma: Unlock offer and demand
ma->ma: Delete match
note over ma: Log match deleted
ma-->>ow --
@enduml
